{
  "$GMRoomUI":"",
  "%Name":"RoomUI",
  "children":[
    {"$GMRUILayer":"v1","%Name":"CombatVictory","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_4","alignItems":2,"children":[
            {"$GMRTextItem":"v3","%Name":"text_BF9D29D","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_BF9D29D","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Victory","wrap":false,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":38.0,},"justifyContent":1,"name":"FlexPanel_4","nodeColour":4294095688,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":190.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"CombatVictory","nodeColour":4286728434,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"CombatGameOver","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_4","alignItems":2,"children":[
            {"$GMRTextItem":"v3","%Name":"text_1DC42B62","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_1DC42B62","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Game Over","wrap":false,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":38.0,},"justifyContent":1,"name":"FlexPanel_4","nodeColour":4294095688,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":190.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"CombatGameOver","nodeColour":4286728434,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"CombatHealth","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_3","alignItems":2,"alignSelf":3,"children":[
            {"$GMRTextItem":"v3","%Name":"player_hp","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"player_hp","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"HP: 20","wrap":false,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":38.0,},"justifyContent":1,"name":"FlexPanel_3","nodeColour":4294068373,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":190.0,},},
        {"$GMRFlexPanel":"","%Name":"FlexPanel_3","alignItems":2,"alignSelf":3,"children":[
            {"$GMRTextItem":"v3","%Name":"enemy_hp","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"enemy_hp","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"HP: 20","wrap":false,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":38.0,},"justifyContent":1,"name":"FlexPanel_3","nodeColour":4294068373,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":190.0,},},
      ],"flexDirection":2,"gridX":32,"gridY":32,"justifyContent":3,"name":"CombatHealth","nodeColour":4282959858,"paddingBottom":{"unit":1,"value":30.0,},"paddingLeft":{"unit":1,"value":30.0,},"paddingRight":{"unit":1,"value":30.0,},"paddingTop":{"unit":1,"value":30.0,},"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"EnemyTurn","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_1","alignItems":2,"children":[
            {"$GMRTextItem":"v3","%Name":"text_54B9DC38","alignment":0,"charSpacing":0.0,"colour":4278190335,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_54B9DC38","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Enemy Turn","wrap":false,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":38.0,},"justifyContent":1,"name":"FlexPanel_1","nodeColour":4282941682,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":190.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"EnemyTurn","nodeColour":4289851976,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"PlayerTurn","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel","alignItems":2,"children":[
            {"$GMRTextItem":"v3","%Name":"text_20CCB4F5","alignment":0,"charSpacing":0.0,"colour":4294901760,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_20CCB4F5","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Player's Turn","wrap":false,"x":-3.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":38.0,},"justifyContent":1,"name":"FlexPanel","nodeColour":4294068451,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":190.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"PlayerTurn","nodeColour":4282970831,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"AttackMenu","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"AttackButton","alignItems":2,"children":[
            {"$GMRFlexPanel":"","%Name":"Text","alignItems":2,"children":[
                {"$GMRTextItem":"v3","%Name":"text_6B7F4FF7","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_6B7F4FF7","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Attack","wrap":false,"x":0.0,"y":0.0,},
              ],"flexDirection":0,"height":{"unit":3,"value":19.0,},"justifyContent":1,"marginBottom":{"unit":1,"value":10.0,},"marginLeft":{"unit":1,"value":10.0,},"marginRight":{"unit":1,"value":10.0,},"marginTop":{"unit":1,"value":10.0,},"name":"Text","nodeColour":4294090312,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":96.0,},},
            {"$GMRInstance":"v4","%Name":"inst_43BAE9D3","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_43BAE9D3","objectId":{"name":"obj_button","path":"objects/obj_button/obj_button.yy",},"properties":[
                {"$GMOverriddenProperty":"v1","%Name":"","name":"","objectId":{"name":"obj_button","path":"objects/obj_button/obj_button.yy",},"propertyId":{"name":"button_id","path":"objects/obj_button/obj_button.yy",},"resourceType":"GMOverriddenProperty","resourceVersion":"2.0","value":"0",},
              ],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"AttackButton","nodeColour":4285286642,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":32.0,},},
        {"$GMRFlexPanel":"","%Name":"ItemButton","alignItems":2,"children":[
            {"$GMRFlexPanel":"","%Name":"Text","alignItems":2,"children":[
                {"$GMRTextItem":"v3","%Name":"text_788224E6","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_788224E6","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Item","wrap":false,"x":0.0,"y":0.0,},
              ],"flexDirection":0,"height":{"unit":3,"value":19.0,},"justifyContent":1,"marginBottom":{"unit":1,"value":10.0,},"marginLeft":{"unit":1,"value":10.0,},"marginRight":{"unit":1,"value":10.0,},"marginTop":{"unit":1,"value":10.0,},"name":"Text","nodeColour":4294090312,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":96.0,},},
            {"$GMRInstance":"v4","%Name":"inst_2CDD0CF0","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_2CDD0CF0","objectId":{"name":"obj_button","path":"objects/obj_button/obj_button.yy",},"properties":[
                {"$GMOverriddenProperty":"v1","%Name":"","name":"","objectId":{"name":"obj_button","path":"objects/obj_button/obj_button.yy",},"propertyId":{"name":"button_id","path":"objects/obj_button/obj_button.yy",},"resourceType":"GMOverriddenProperty","resourceVersion":"2.0","value":"1",},
              ],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"ItemButton","nodeColour":4285286642,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":32.0,},},
      ],"flexDirection":0,"gapRow":10.0,"gridX":32,"gridY":32,"justifyContent":1,"name":"AttackMenu","nodeColour":4283822664,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"DefenseMenu","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"DefenseButton","alignItems":2,"children":[
            {"$GMRFlexPanel":"","%Name":"Text","alignItems":2,"children":[
                {"$GMRTextItem":"v3","%Name":"text_715355C4","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_715355C4","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Defend","wrap":false,"x":0.0,"y":0.0,},
              ],"flexDirection":0,"height":{"unit":3,"value":19.0,},"justifyContent":1,"marginBottom":{"unit":1,"value":10.0,},"marginLeft":{"unit":1,"value":10.0,},"marginRight":{"unit":1,"value":10.0,},"marginTop":{"unit":1,"value":10.0,},"name":"Text","nodeColour":4294090312,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":96.0,},},
            {"$GMRInstance":"v4","%Name":"inst_1751862F","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_1751862F","objectId":{"name":"obj_button","path":"objects/obj_button/obj_button.yy",},"properties":[
                {"$GMOverriddenProperty":"v1","%Name":"","name":"","objectId":{"name":"obj_button","path":"objects/obj_button/obj_button.yy",},"propertyId":{"name":"button_id","path":"objects/obj_button/obj_button.yy",},"resourceType":"GMOverriddenProperty","resourceVersion":"2.0","value":"2",},
              ],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"DefenseButton","nodeColour":4285286642,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":32.0,},},
      ],"flexDirection":0,"gapRow":10.0,"gridX":32,"gridY":32,"justifyContent":1,"name":"DefenseMenu","nodeColour":4283822664,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"RoamingUI","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_2","alignItems":2,"children":[
            {"$GMRTextItem":"v3","%Name":"text_6F146B98","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_6F146B98","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Press Space to Interact","wrap":false,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":38.0,},"justifyContent":1,"name":"FlexPanel_2","nodeColour":4282970766,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":190.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":0,"name":"RoamingUI","nodeColour":4294073672,"paddingBottom":{"unit":1,"value":20.0,},"paddingLeft":{"unit":1,"value":20.0,},"paddingRight":{"unit":1,"value":20.0,},"paddingTop":{"unit":1,"value":20.0,},"resourceType":"GMRUILayer","resourceVersion":"2.0",},
  ],
  "locked":false,
  "name":"RoomUI",
  "parent":{
    "name":"Cinematic Disaster",
    "path":"Cinematic Disaster.yyp",
  },
  "resourceType":"GMRoomUI",
  "resourceVersion":"2.0",
  "viewspaceChildren":[],
  "visible":true,
}